export const skillsData = [
    {
        src:"https://cdn.jsdelivr.net/gh/devicons/devicon/icons/javascript/javascript-original.svg",
        alt:'javascript'
    },
    {
        src:"https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nextjs/nextjs-original.svg",
        alt:'next'
    },
    {
        src:"https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg",
        alt:'react'
    },
    {
        src:"https://cdn.shopify.com/s/files/1/0608/1160/8311/files/UE_Logo_stacked_unreal-engine_black.png?v=1638540869",
        alt:'unreal'
    },
    {
    src:"https://cdn.jsdelivr.net/gh/devicons/devicon/icons/vscode/vscode-original.svg",
    alt:'vscode'
    },
    {
    src:"https://cdn.jsdelivr.net/gh/devicons/devicon/icons/socketio/socketio-original.svg",
    alt:'socketio'
    },
    {
        src:"https://cdn.jsdelivr.net/gh/devicons/devicon/icons/woocommerce/woocommerce-original.svg",
        alt:'woocomerce'
    },
    {
        src:"https://cdn.shopify.com/s/files/1/0608/1160/8311/files/shopify-logo-png-6880.png?v=1638560358",
        alt:'shopify'
    },
    {
        src:"https://cdn.jsdelivr.net/gh/devicons/devicon/icons/visualstudio/visualstudio-plain.svg",
        alt:'vstudio'
    },
    {
        src:"https://cdn.jsdelivr.net/gh/devicons/devicon/icons/wordpress/wordpress-original.svg",
        alt:'woordpress'
    },
    {
        src:"https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nodejs/nodejs-original-wordmark.svg",
        alt:'node'
    },
    {
        src:"https://cdn.jsdelivr.net/gh/devicons/devicon/icons/yarn/yarn-original.svg",
        alt:'yarn'
    },
    {
        src:"https://cdn.jsdelivr.net/gh/devicons/devicon/icons/typescript/typescript-original.svg",
        alt:'typescript'
    },
    {
        src:"https://cdn.shopify.com/s/files/1/0608/1160/8311/files/chakra.png?v=1638540967",
        alt:'chakra'
    },
    {
        src:"https://cdn.jsdelivr.net/gh/devicons/devicon/icons/tailwindcss/tailwindcss-original-wordmark.svg",
        alt:'tailwind'
    },
    {
        src:"https://cdn.shopify.com/s/files/1/0608/1160/8311/files/1_p1TndLk3UsGPBsM7qHPZIw.png?v=1638560482",
        alt:'stylecomponents'
    },
    {
        src:"https://cdn.jsdelivr.net/gh/devicons/devicon/icons/gatsby/gatsby-plain.svg",
        alt:'gatsby'
    },
    {
        src:"https://cdn.jsdelivr.net/gh/devicons/devicon/icons/redux/redux-original.svg",
        alt:'redux'
    },
    {
        src:"https://cdn.jsdelivr.net/gh/devicons/devicon/icons/vuejs/vuejs-original.svg",
        alt:'vue'
    },
    {
        src:"https://cdn.jsdelivr.net/gh/devicons/devicon/icons/threejs/threejs-original.svg",
        alt:'three'
    },
    {
        src:"https://cdn.shopify.com/s/files/1/0608/1160/8311/files/Logo_Blender.svg_1.png?v=1638560795",
        alt:'blender'
    },
    {
        src:"https://cdn.jsdelivr.net/gh/devicons/devicon/icons/sass/sass-original.svg",
        alt:'sass'
    },
    {
        src:"https://cdn.jsdelivr.net/gh/devicons/devicon/icons/electron/electron-original.svg",
        alt:'electron'
    },
    {
        src:"https://cdn.jsdelivr.net/gh/devicons/devicon/icons/css3/css3-original.svg",
        alt:'css3'
    },
    {
        src:'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/cplusplus/cplusplus-original.svg',
        alt:'c++'
    },
    {
        src:'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/amazonwebservices/amazonwebservices-original-wordmark.svg',
        alt:'amazon'
    },
    {
        src:"https://cdn.jsdelivr.net/gh/devicons/devicon/icons/aftereffects/aftereffects-original.svg",
        alt:'afx'
    },
    {
        src:"https://cdn.jsdelivr.net/gh/devicons/devicon/icons/bootstrap/bootstrap-original.svg",
        alt:'bootstrap'
    },
    {
        src:"https://cdn.jsdelivr.net/gh/devicons/devicon/icons/firebase/firebase-plain.svg",
        alt:'firebase'
    },
    {
        src:"https://cdn.jsdelivr.net/gh/devicons/devicon/icons/git/git-original.svg",
        alt:'git'
    },
    {
        src:"https://cdn.jsdelivr.net/gh/devicons/devicon/icons/github/github-original.svg",
        alt:'github'
    },
    {
        src:"https://cdn.jsdelivr.net/gh/devicons/devicon/icons/graphql/graphql-plain.svg",
        alt:'graphql'
    },
    {
        src:"https://cdn.jsdelivr.net/gh/devicons/devicon/icons/gulp/gulp-plain.svg",
        alt:'gulp'
    },
    {
        src:"https://cdn.jsdelivr.net/gh/devicons/devicon/icons/html5/html5-original.svg",
        alt:'html'
    },
    {
        src:"https://cdn.jsdelivr.net/gh/devicons/devicon/icons/materialui/materialui-original.svg",
        alt:'materialui'
    },
    {
        src:"https://cdn.jsdelivr.net/gh/devicons/devicon/icons/mongodb/mongodb-original.svg",
        alt:'mongo'
    },
    {
        src:"https://cdn.jsdelivr.net/gh/devicons/devicon/icons/npm/npm-original-wordmark.svg",
        alt:'npm'
    },
    {
        src:"https://cdn.shopify.com/s/files/1/0608/1160/8311/files/descarga_13.png?v=1638573046",
        alt:'davinci'
    },
    {
        src:"https://cdn.jsdelivr.net/gh/devicons/devicon/icons/photoshop/photoshop-plain.svg",
        alt:'photoshop'
    },
    {
        src:"https://cdn.jsdelivr.net/gh/devicons/devicon/icons/premierepro/premierepro-plain.svg",
        alt:'premier'
    },
    {
        src:"https://cdn.jsdelivr.net/gh/devicons/devicon/icons/qt/qt-original.svg",
        alt:'qt'
    }


    
    

]